server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQATOnIrCagRmSGfeohEsf7Mf1AFa0fsAE2bYWnmKVDBt7GJKZG9Crq9fUmpfiysns6d+ZEP0H8cztw0KOvpsVtGjY6EgGxB+9iKGlNA8iQsq1zvT9vYtPPPS9ArrPMPZx1XUjNaz2BbhJ1qL7SaVHsgHvYL3vJLWwbkwAfgPoXct6AGDRfX3AZCh+QnwJ/aDBtM0ck4nOJDFsQ6MzM4dPUVIPIY1COj9IwtlKlxGn/HmxCT71K+IqanEmNleb0iWhwszm34h79i8m7Qix+V6fB49YK0RJ8EHOygYsqGLj7VXjGydYLYC4fwnnfKvAJ8J0A9HunfcMzBjqCeZab2XJEbK+ru3CAPHguQeQc+YbZn0Nft4peREXiRvA+tbM0HQgeZ93eh6K2bylSRUR3wJi8g15iHRWtmMOtDc5r9aQImzw=='

file:
  storage:
    enabled: true
    domain: http://127.0.0.1:9000
    accessKey: VV2V7IK1NOEY636AGLKO
    secretKey: iUlGKax02hsgClCLPCpy50DpD6ltW1kOV4pYcT2A
    bucketName: '{cipher}AQBWIOh2B7UrML/VRKi8WX3EbqOxkHCnRpRTYfu+RYcHMK+C4/bsRsTKmwnW+D7KNVA4aj2CAlk8w9Gr1tNjJeoVtu8x177GF3Z7+wzuQAAiQ1u4UwHap18ZD7g/cuJNN3sLyBOEFOsS0nT+pk8N3tZlEngaq9gUfs9mi2Oyh8e06Nj98yaKgI7h9uZ5mUF96ZPbyXbTsU9EYwFD4vFLuQTUpbp3Ny7NlRtAU0wNqHLuj6mTHclOcH/rnp5P2ZaA64yDblBR7swEwtE+jDTl6xldBNT0v2Wr+9odZlFRPNkfRC8164quGiSxWuIWKWToqFrK8sefu5RTrmNfNiPHJaBy1Vjq4VqrlGPPG2JfprFiHtsfyZwqMzsYqAw+VKv4jAilHjJFeXlRUcw1tCWwgbWh'