server:
  port: 8085

spring:
  datasource:
    url: '{cipher}AQCFxEROoYpdZSGw4MPRpLsx84hCnwE++y167QF0KzScEpWpbPi/Tpw3GKcOCr99d+ikGX0/hYP1yx1oSGQgiGd2iEK8OyiqoN6s56pU7X5cHu3sponJ5rN5yomzvsO/z/DWUxBBUBZYwi+j+HZozrtcUPEo8cjohWpw72MUehmb+6PD61oxHij4gi4vUI2O8vOV6EIfxfEhIUHS6vLeCaB95pF7gbw2GzKnCNxu1qCW0WEf4b/G/AYd3WVybYP5k1CIE2bImJTL+AYCJaRqCihWdtPkdSjLJn8OvjHNeEP3dpbdWPejUv+I/XZEOcslcP1upNu28wCk+EJMMVmUBnNgt5TWDSHl86LwXQBNReQZhuZY3tZISMgUPRXZTSYPY8plp9MqAMmafWdHufEAm3qH'

bpmn:
  ribbon:
    listOfServers: http://localhost:9999