server:
  port: 8083

spring:
  datasource:
    url: '{cipher}AQArntvoLXUJALH1AzumgLJ1/C1pOqBLrryoSzyz6S0lBTYH0Nnc1C4qe9WlqiiW3elQoHvnyGZIJp5SopK8/Zm+65DekDSoE+YeKB5vkJLQdwp5KHkdseIzYl2fTOWH27SFm/eRnv8rZ2XH8Zru2bHFFOVKCGkMh0IFOW6I46io7FWPQgJgXf2PgT2hwIlhxe2F4HKwdSDb++vPrzOBudMUGNwQyAkMYdGV1eD6FS64zl+gmZg7FMBA6hHOuOZEgdhLxISPzyXczucP4yZBr8+K2mQMZcAj+UYUnlJXbc9HqWBHA+p/asOyNewAEiIPrBhP07G+LIAM5EsYQbB2mxftP9qaZhDv/ghGAw7Iyuq2AvLLUoECQ2PN+9gebhAo2Z3ogCKZCv2+qDqnk5Znf8mV5dBfEINYJV6/tlibM0x30dMEfHdJOtvjgR2f8VwUk/A='

bpmn:
  username: '{cipher}AQB5/5krETkJarsXzf5WGcthKVMXE7DdRQtSwOEfgh2S99rvduH+xIUYlWhcm3gCRd6SXp+Y5q7O/lchtCcwXk4r1Og3xlIP6F5+5B6/vzKJzfbfXnf9zNedAL7PGTtVXtkCgcLGfOJCwgRq/OOJkJ4CxVyEqPz8oKQg6GcIxp0W7l5ppIIOIIPesASCq22VBgj6edFTex0XJbtqR+lpOk6tWnbu9H++ssX2CN+z/T2yq6mT1L73DlbMRq9SDhUhS5o+vO8wTakNAc/HsAfywerb92HTmYRQ6oJ85obsJYsnVnw6ajxYwyxKyXai/Zcm56a9XFVazgO43JzFB/m/lGJvltvsh1m9AAqK4GG/hDrcI70wOxCDp3Zsa0HzqIvlaMdfCSDTFrweySznTBmH5HEh'
  password: '{cipher}AQB45FB1iw1rKEfijhlo9PnGqIaDmk9ysdqCe0TOAI1Zn2FA2MXDEI0W3IwYT5K9VTEVVlnzYQp9i88jS+j1s58UYKsZFFT1gUpk6z92X8juNkdukDrheFwQ8EvrSLJNum9OGLzvmWUfj0Cm0RCTtjd0JD7r6Aum08VncihEDphaYs8e2/vWDxNyQ4yqM0eyvgGNDbU4bYHAd8QmwFzfGT0ctVyBQ+JeINztVrj8y6QTnDdc5Y8239g6b4p4ZEwAZ3VSugObvCOrXn1KfQTjZNmwVi6YF+19IX2FHimMHgkHNM+cNWpFQ9P4DeyZc+yRQeIn39cWLs4+MZ20ljeXQEB/9aZb30jhiAxMQhXBotNmoN/knvmXKlOINRXd01ynRDc='
  ribbon:
    listOfServers: http://localhost:9999