server:
  port: 8083

spring:
  datasource:
    url: '{cipher}AQArntvoLXUJALH1AzumgLJ1/C1pOqBLrryoSzyz6S0lBTYH0Nnc1C4qe9WlqiiW3elQoHvnyGZIJp5SopK8/Zm+65DekDSoE+YeKB5vkJLQdwp5KHkdseIzYl2fTOWH27SFm/eRnv8rZ2XH8Zru2bHFFOVKCGkMh0IFOW6I46io7FWPQgJgXf2PgT2hwIlhxe2F4HKwdSDb++vPrzOBudMUGNwQyAkMYdGV1eD6FS64zl+gmZg7FMBA6hHOuOZEgdhLxISPzyXczucP4yZBr8+K2mQMZcAj+UYUnlJXbc9HqWBHA+p/asOyNewAEiIPrBhP07G+LIAM5EsYQbB2mxftP9qaZhDv/ghGAw7Iyuq2AvLLUoECQ2PN+9gebhAo2Z3ogCKZCv2+qDqnk5Znf8mV5dBfEINYJV6/tlibM0x30dMEfHdJOtvjgR2f8VwUk/A='

bpmn:
  username: '{cipher}AQAINM2+IYFzeya1DwRpGb+xvGndkY9rD2+Mj5PW1NDFua2cH5IcQm+AmZr3TAtP1RJ9zg3qPMpMN1jP2jow91SbFIxLjpmNn958A4/37HzqhRHpRNk67B22sOowW1OFl43tXsGOwNWI0eA7Co+dzEqlWj8KX8MFK9U9r4KxF74r8O65udX6y/DALjt/X110oRem3ctROVZ3d9kbWxNOkrE9Z9fWYQJB5Jp2oiTFEtSJYyMLLu/BaYny7gP9xAFINNEbO9g3MxyKxiFSszbaHzMh0hjMPuZE0srC3Ry0Hr72v6w1Peu0Ma5L4YKL2f96uly85eezPl82WssT1qxeKy7oj8O8m44EFtkDvTslDY62Ym/JNedidyyxz4Vx0daAn3qcZbqi++w9nCCOnnbN5LyC'
  password: '{cipher}AQBl4pHwK4QkVq7Opm2Uu4fQBvP1+QPdS7bjV/6B1iJSqoxQ6A+c3rthnALbnMTogq6g69RwBfe+uZKvZTE4g56XSsxPqvy37Bvoy37cPlC/kPWuXSKECrIpQAe/xg4d3Iqn6/LLP8VeuqisK2uTQrjkR28dn7CjK8L01IyOr01E1f6lwJzrm9D7eM9gDFbq6F870CY9QaX9J+V1gOdg9zA2OC+OAfH8WmS33EyzQEhLUk5lhrNvUBB2sbb+2i8eiqsF0wUYAcxm9SovNyRdmvgZA1mNxuT6vckGOvvPBqi66MudinBkfAmV3Yh/lD3Sw12tVyCuj5IxlE1IYV+WWF3KfUMUGTc2h5uz3NjLqHN6oDv6NEwgLyRAyb0YWqDWqTA='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999